### PR TITLE
Update README.md to support Remix 2.0

### PR DESCRIPTION
**Pull request by mahmoudmoravej**
Some types have been changed since Remix 2.0. This commit fixes the readme to support Remix 2.0

### CODE REVIEW

**Comment by mahmoudmoravej** [comment]
cc @pbteja1998 if you have time to review this small changes

**Comment by pbteja1998** [comment]
Please run lint and format commands to follow prettier setup that is configured.

**Comment by refactornator** [comment]
The Readme being out of date caused me some confusion when I was getting started with this library. Can someone with write access merge these changes?

**Comment by mahmoudmoravej** [comment]
@refactornator thanks for bringing it up. I hope @pbteja1998  (the main owner) takes this into action. I am not sure if other contributers have write access cc @Hansenq
@maddhruv
@MichaelDeBoey
@TheRealFlyingCoder

**Pull request merged**
